seed: 42
hydra:
  run:
    dir: .

experiment:
  task: classification
  ckpt_file_name: resnet18_qr_ocqr_calibration_eyepacs

data:
  repo: eyepacs
  num_workers: 8
  batch_size: 128
  pin_memory: true
  label_type: continuous

check_point:
  model_type: resnet
  base: ./assets/checkpoints/qr/
  resnet18_qr: d765cptl_resnet18_qr_eyepacs_q89_epoch=46-val_loss=0.2322.ckpt

uc:
  csv_path: ./assets/uc_results/
  significance_level: 0.1
  methods: [ordinal_cqr]
  num_classes: 5
  class_wise: true
  class_mapping: {"0": 0, "1": 1, "2": 2, "3": 3, "4": 4}
  thresholds: [0.5, 1.5, 2.5, 3.5]
  cqr:
    lower_idx: 0
    upper_idx: -1

trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  precision: 32

wandb:
  save_dir: ./assets
  entity: gsu-dmlab
  project: uncertainty-eyepacs_classification
  offline: false
