seed: 42
hydra:
  run:
    dir: .

experiment:
  task: regression
  ckpt_file_name: resnet34_qr

data:
  repo: nasa-ibm-ai4science/surya-bench-flare-forecasting
  ref_mask_img: HMI-Mag.2010.12.06_07.00.00.jpg
  flare_index:
    path: ../../assets/data/
    train: train.csv
    val: validation.csv
    test: test.csv
  input_index_path: ../../assets/data/helioviewer_mag_input.csv
  input:
    path: /anvil/projects/x-cis251356/helioviewer/mag
    ext: jpg
    dim: 512
  input_time_delta: [0] #[-60, 0]
  input_stat_path: ../../assets/data/los_mag_stat.yaml
  label_type: max_intensity
  ordinal_label_type: max_goes_class
  limb_mask_path: ../../assets/data/limb_mask.npy
  target_norm_type: log
  channel: hmi_m
  scaler_mul: 1
  scaler_shift: -127.5
  scaler_div: 127.5
  # for dataloader
  num_workers: 2
  batch_size: 256
  pin_memory: true

model:
  save_ckpt_path: /anvil/projects/x-cis251356/check_point/FlareTorch/qr/
  ckpt: null
  module_type: "qr" # mcp, qr
  # module specific
  mcp:
    num_forwards: 100
  qr:
    quantiles: [0.2, 0.5, 0.8]
  
  # base model
  type: resnet34
  resnet34:
    in_channels: 1
    time_steps: 1
    p_drop: 0.5
    
  loss:
    type: mse

optimizer:
  type: adamw
  lr: 5e-5
  weight_decay: 0.01

scheduler:
    use: cosine_warmup # The switch
    monitor: val_loss 
    # Define available strategies
    cosine_warmup:
      total_steps: 1000
      warmup_ratio: 0.1 # Default 10% warmup
    plateau:
      mode: min
      factor: 0.1
      patience: 10

trainer:
  accelerator: gpu
  devices: 2
  num_nodes: 1
  max_epochs: 150
  precision: 32
  log_every_n_steps: 50
  limit_train_batches: 3000
  limit_val_batches: 1500
  strategy: auto

wandb:
  save_dir: ../../assets
  entity: gsu-dmlab
  project: uncertainty-flare-regression
  log_model: false
  notes: Resnet34 backbone and QR
  offline: true
  save_code: false
  tag: ["resnet34", "qr", "regression"] # backbone model, head type, task
