seed: 42
hydra:
  run:
    dir: .

experiment:
  task: classification
  ckpt_file_name: resnet18_binomial_calibration_eyepacs

data:
  repo: eyepacs
  num_workers: 8
  batch_size: 128
  pin_memory: true
  label_type: ordinal

check_point:
  model_type: resnet18_binomial
  base: ./assets/checkpoints/cls/
  resnet18_binomial_cls: 3tq6447d_resnet18_binomial_eyepacs_epoch=15-val_loss=1.0718.ckpt

uc:
  csv_path: ./assets/uc_results/
  significance_level: 0.1
  methods: [binomial_lac]
  num_classes: 5
  class_wise: true
  class_mapping: {"0": 0, "1": 1, "2": 2, "3": 3, "4": 4}

trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  precision: 32

wandb:
  save_dir: ./assets
  entity: gsu-dmlab
  project: uncertainty-eyepacs_classification
  offline: false
