seed: 42
defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

experiment:
  task: classification
  ckpt_file_name: resnet18_binomial_cls

data:
  repo: nasa-ibm-ai4science/surya-bench-flare-forecasting
  ref_mask_img: null
  flare_index:
    path: /scratch/users/jhong36/data/
    train: train.csv
    val: validation.csv
    test: test.csv
  input_zarr_path: /scratch/users/jhong36/data/sdo_512.zarr
  input_time_delta: [0]
  input_stat_path: ./assets/stats/los_mag_stat.yaml
  label_type: max_goes_class
  filter_numeric_target_column: max_intensity
  fq_max_intensity_exclusion_threshold: 1.0e-7
  excluded_goes_classes: [M0.9]
  limb_mask_path: ./assets/limb_mask.npy
  target_norm_type: multi_class
  channel: hmi_m
  # for dataloader
  num_workers: 6
  batch_size: 256
  pin_memory: true

model:
  save_ckpt_path: ./assets/checkpoints/cls/
  ckpt: null
  module_type: cls # mcp, qr, cls
  
  # base model
  type: resnet18_binomial
  resnet18_binomial:
    in_channels: 1
    time_steps: 1
    num_classes: 5
    p_drop: 0.5
    
  loss:
    type: cross_entropy
    class_weights: [1.0, 1.0, 1.0, 1.0, 1.0]

optimizer:
  type: adamw
  lr: 5e-5
  weight_decay: 0.01

scheduler:
    use: cosine_warmup
    monitor: val_loss 
    cosine_warmup:
      total_steps: 1000
      warmup_ratio: 0.1
    plateau:
      mode: min
      factor: 0.1
      patience: 10

trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 300
  precision: 32
  log_every_n_steps: 50
  limit_train_batches: null
  limit_val_batches: null
  strategy: auto

wandb:
  save_dir: ./assets
  entity: gsu-dmlab
  project: uncertainty-flare-classification
  log_model: false
  notes: Resnet18 binomial backbone and Classification
  offline: false
  save_code: false
  tag: ["resnet18_binomial", "cls"] # backbone model, head type, task
