seed: 42
defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

experiment:
  task: classification
  ckpt_file_name: resnet18_cls_eyepacs

data:
  repo: eyepacs
  num_workers: 8
  batch_size: 128
  pin_memory: true
  label_type: ordinal

model:
  save_ckpt_path: ./assets/checkpoints/cls/
  ckpt: u5zr2xfk_resnet18_cls_eyepacs_epoch=11-val_loss=0.8303.ckpt
  module_type: cls
  
  type: resnet18
  resnet18:
    in_channels: 3
    time_steps: 1
    num_classes: 5
    p_drop: 0.5
    
  loss:
    type: cross_entropy
    class_weights: [1.0, 1.0, 1.0, 1.0, 1.0]

optimizer:
  type: adamw
  lr: 1e-4
  weight_decay: 0.01

scheduler:
    use: cosine_warmup
    monitor: val_loss 
    cosine_warmup:
      total_steps: 1000
      warmup_ratio: 0.1
    plateau:
      mode: min
      factor: 0.1
      patience: 5

trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 100
  precision: 32
  log_every_n_steps: 10
  limit_train_batches: null
  limit_val_batches: null
  strategy: auto

wandb:
  save_dir: ./assets
  entity: gsu-dmlab
  project: uncertainty-eyepacs-classification
  log_model: false
  notes: Resnet18 backbone on EyePACS
  offline: false
  save_code: false
  tag: ["resnet18_cls", "cls", "eyepacs"]
