seed: 42
defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

experiment:
  task: regression
  ckpt_file_name: resnet18_qr_eyepacs

data:
  repo: eyepacs
  num_workers: 8
  batch_size: 128
  pin_memory: true
  label_type: continuous

model:
  save_ckpt_path: ./assets/checkpoints/qr/
  ckpt: null
  module_type: qr
  qr:
    quantiles: [0.05, 0.5, 0.95]
  
  type: resnet18
  resnet18:
    in_channels: 3
    time_steps: 1
    p_drop: 0.5
    num_classes: 1
    
  loss:
    type: pinball

optimizer:
  type: adamw
  lr: 1e-5
  weight_decay: 0.1

scheduler:
    use: cosine_warmup
    monitor: val_loss 
    cosine_warmup:
      total_steps: 1000
      warmup_ratio: 0.1
    plateau:
      mode: min
      factor: 0.1
      patience: 5

trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 100
  precision: 32
  log_every_n_steps: 10
  limit_train_batches: null
  limit_val_batches: null
  strategy: auto

wandb:
  save_dir: ./assets
  entity: gsu-dmlab
  project: uncertainty-eyepacs-classification
  log_model: false
  notes: Resnet18 backbone on EyePACS (QR)
  offline: false
  save_code: false
  tag: ["resnet18", "qr", "eyepacs"]
